# Creator suggestion for influencer sponsorship

## Part 5: Use Auto-ML on the outreach of the brand on positive videos
---

### Content Workflow:

- [Instatiate libraries](#Instatiate-libraries)
- [Creating a predictive model on the popularity of video released](#Creating-a-predictive-model-on-the-popularity-of-video-released)

## Instatiate libraries

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Import progress bar
from tqdm.notebook import tqdm_notebook
tqdm_notebook.pandas()

# Import tqdm
from tqdm import tqdm

# Modelling
from sklearn.model_selection import train_test_split

# Expand display of the dataframe
pd.options.display.max_colwidth = 500

In [3]:
### Load Saved datasets
df_m = pd.read_csv('./output/df_m.csv')

## Creating a predictive model on the popularity of video released

In [4]:
df_m.drop(columns=['Unnamed: 0','Title'], inplace= True)
print(df_m.shape)
print(df_m.info())
df_m.head()

(15718, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15718 entries, 0 to 15717
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Channel_name      15718 non-null  object
 1   View_count        15716 non-null  float64
 2   Like_count        15717 non-null  float64
 3   Comment_count     15718 non-null  int64
 4   View_per_day      15716 non-null  float64
 5   Like_per_day      15717 non-null  float64
 6   Comment_per_day   15718 non-null  float64
 7   Engagement_ratio  15716 non-null  float64
 8   Popular_target    15718 non-null  int64
 9   Growth            15718 non-null  float64
dtypes: float64(7), int64(2), object(1)
memory usage: 1.2+ MB
None

,Channel_name,View_count,Like_count,Comment_count,View_per_day,Like_per_day,Comment_per_day,Engagement_ratio,Popular_target,Growth
0,Tina Huang,16757.0,1113.0,143,9509.002236,631.587963,81.147420,0.853375,1,36.992072
1,Tina Huang,46006.0,2457.0,321,3555.394838,189.879692,24.807237,0.697735,1,36.992072
2,Tina Huang,77435.0,4551.0,379,2985.210750,175.446428,14.610898,0.489443,1,36.992072
3,Tina Huang,44254.0,2683.0,196,1306.302100,79.197554,5.785583,0.442898,1,36.992072
4,Tina Huang,207709.0,11628.0,799,4726.001495,264.571807,18.179642,0.384673,1,36.992072

## Modelling on Numerical Data

In [4]:
features = [col for col in df_m.columns if col != 'Popular_target']
X = df_m[features]
y = df_m['Popular_target']

In [9]:
features = [col for col in df_m.columns if col != 'Channel_name']
X1 = df_m[features]
y1 = df_m['Channel_name']

In [6]:
# Creating holdout set data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05,
                                                    stratify=y, random_state=42)

In [10]:
# Creating holdout set data
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.05,
                                                    stratify=y, random_state=42)

## Creating Pycaret dataset

In [ ]:
#!pip install pycaret

In [7]:
from pycaret.regression import *

In [11]:
pyca_data1 = pd.concat([X1_train, y1_train], axis=1)

In [8]:
pyca_data = pd.concat([X_train, y_train], axis=1)

In [9]:
pyca_model = setup(data=pyca_data,
                   target='Popular_target',
                   session_id=123)

In [10]:
best=compare_models(exclude=['ransac'])

Thus, lightgbm would be used for the producation model due to the shorter computational time to the $R^2$ score.

## Conclusion

The prediction model of the dataset are for client to check the the popularity of the video prior to releasing the video on social media. 
The lightgbm model will be further fine-tunned to have a better score.